version: "3.8"

services:
  
  web:    
    build: .    
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    tty: true    
    stdin_open: true
    container_name: ${COMPOSE_PROJECT_NAME}_app
    expose:
      - ${PORT}
    links:
      - db
    env_file:
      - .env
    restart: unless-stopped
      
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
          - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
          
volumes:
  postgres_data: