version: "3.8"

services:
  

  web:    
    build: ./src
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - cache
    tty: true    
    stdin_open: true
    container_name: ${COMPOSE_PROJECT_NAME}_app
    expose:
      - ${PORT}
    links:
      - db
      - cache
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src:/code


  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
          - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
          
  cache:
    restart: unless-stopped
    image: redis:6.0
    container_name: ${COMPOSE_PROJECT_NAME}_cache
    networks:
        - default
    ports:
     - "6379:6379"


volumes:
  postgres_data:

networks:
    default:
        name: ${COMPOSE_PROJECT_NAME}_default