version: "3.8"

services:

  web:    
    build: ./src
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - rabbit
    tty: true    
    stdin_open: true
    container_name: ${COMPOSE_PROJECT_NAME}_app
    expose:
      - ${PORT}
    links:
      - db
      - rabbit
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src:/code

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
          - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbit:
    container_name: rabbit
    networks:
      - main
    image: rabbitmq:3.9.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure
    volumes: 
      - ./data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBIT_URL=rabbit

volumes:
  postgres_data:

networks:
  main: