# Generated by Django 3.1.8 on 2022-01-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configapp',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='configapp',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='configapp',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização'),
        ),
    ]
