# Generated by Django 3.1.8 on 2022-01-16 02:29

from django.db import migrations, models
import ranking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('registration', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='É importante que a imagem seja em PNG', upload_to=ranking.models.upload_rank_images, verbose_name='Imagem do Rank')),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
            },
        ),
    ]
