# Generated by Django 3.1.8 on 2022-01-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreuser',
            options={'verbose_name': 'Núcleo de Autenticação', 'verbose_name_plural': 'Núcleos de Autenticação'},
        ),
    ]
