# Generated by Django 3.1.8 on 2022-01-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_auth', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project_auth.client', verbose_name='Dono'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory', verbose_name='Sub-Categoria'),
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.Tag'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products'),
        ),
        migrations.AddField(
            model_name='opensearch',
            name='dislike_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dislike'),
        ),
        migrations.AddField(
            model_name='opensearch',
            name='like_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.like'),
        ),
        migrations.AddField(
            model_name='opensearch',
            name='own_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AddField(
            model_name='like',
            name='lista',
            field=models.ManyToManyField(blank=True, to='products.Products'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='lista',
            field=models.ManyToManyField(blank=True, to='products.Products'),
        ),
    ]
