# Generated by Django 3.1.8 on 2022-01-15 18:05

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220107_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('registration', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro no Sistema')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização no Sistema')),
                ('name', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': "Tag's",
            },
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro no Sistema'),
        ),
        migrations.AddField(
            model_name='category',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização no Sistema'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productimages',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro no Sistema'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização no Sistema'),
        ),
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro no Sistema'),
        ),
        migrations.AddField(
            model_name='products',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização no Sistema'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro no Sistema'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização no Sistema'),
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.Tag'),
        ),
    ]
