# Generated by Django 3.1.8 on 2022-02-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220201_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensearch',
            name='match',
            field=models.ManyToManyField(blank=True, related_name='matches', to='products.Products', verbose_name='Lista de Combinações'),
        ),
    ]
