# Generated by Django 3.1.8 on 2022-01-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220118_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='uuid',
            new_name='id',
        ),
    ]
