# Generated by Django 3.1.8 on 2021-12-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211218_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Imagem do Produto', 'verbose_name_plural': 'Imagens do Produto'},
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='position',
        ),
    ]
