# Generated by Django 3.1.8 on 2022-01-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220115_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='category',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização'),
        ),
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='products',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='products',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização'),
        ),
    ]
