# Generated by Django 3.1.8 on 2022-02-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversare', '0002_auto_20220201_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='displayed',
            field=models.BooleanField(default=False),
        ),
    ]
