# Generated by Django 3.1.8 on 2022-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversare', '0003_messagemodel_displayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='displayed',
            field=models.BooleanField(default=False, verbose_name='Visualizado'),
        ),
    ]
