# Generated by Django 3.1.8 on 2022-02-12 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversare', '0004_auto_20220207_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('registration', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
                ('level', models.CharField(choices=[('success', 'Sucesso'), ('info', 'Informação'), ('warning', 'Perigo'), ('error', 'Erro')], default='info', max_length=30, verbose_name='Nivel')),
                ('unread', models.BooleanField(db_index=True, default=True, verbose_name='Lido')),
                ('message', models.TextField(max_length=2000, verbose_name='Mensagem')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ('-registration',),
                'index_together': {('recipient', 'unread')},
            },
        ),
    ]
