# Generated by Django 3.1.8 on 2022-01-19 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('registration', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('users', models.ManyToManyField(help_text='Usuários conectados ao chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicRoomChatMessageManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('registration', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicRoomChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('registration', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
                ('content', models.TextField(max_length=5000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.publicchatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
