# Generated by Django 3.1.8 on 2021-12-10 00:54

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import src.project_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('active', models.BooleanField(default=True)),
                ('registration', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro no Sistema')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização no Sistema')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Cidade')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='País')),
                ('state', models.CharField(blank=True, max_length=80, verbose_name='Estado')),
                ('neighborhood', models.CharField(blank=True, max_length=80, verbose_name='Bairro')),
                ('street', models.CharField(blank=True, max_length=80, verbose_name='Rua')),
                ('image', models.ImageField(blank=True, default='default_profile.jpeg', null=True, upload_to=src.project_auth.models.upload_perfil_user, verbose_name='Imagem')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de telefone')),
                ('bio', models.CharField(blank=True, max_length=2000, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='products.Category', verbose_name='Categorias Preferidas')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
