# Generated by Django 3.1.8 on 2022-02-01 16:43

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import project_auth.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ranking', '0001_initial'),
        ('products', '0001_initial'),
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('coreuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_auth.coreuser')),
                ('city', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade')),
                ('country', models.CharField(blank=True, max_length=80, null=True, verbose_name='País')),
                ('state', models.CharField(blank=True, max_length=80, null=True, verbose_name='Estado')),
                ('neighborhood', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro')),
                ('street', models.CharField(blank=True, max_length=80, null=True, verbose_name='Rua')),
                ('uuid', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default_profile.jpeg', upload_to=project_auth.models.upload_perfil_user, verbose_name='Imagem de Perfil')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de telefone')),
                ('bio', models.TextField(blank=True, max_length=2000, null=True)),
                ('experience', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999999999, message='Você extrapolou o limite positivamente'), django.core.validators.MinValueValidator(limit_value=-10000, message='Você extrapolou o limite negativamente')])),
                ('categories', models.ManyToManyField(blank=True, to='products.Category', verbose_name='Categorias Preferidas')),
                ('rank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank_of', to='ranking.rank')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('core_auth.coreuser', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
