# Generated by Django 3.1.8 on 2022-01-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
        ('project_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rank',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank_of', to='ranking.rank'),
        ),
    ]
