# Generated by Django 3.1.8 on 2022-01-15 18:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('registration', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro no Sistema')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização no Sistema')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=project_auth.models.upload_rank_images, verbose_name='Imagem do Rank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='experience',
            field=models.IntegerField(default=0, max_length=16, validators=[django.core.validators.MaxValueValidator(-10000, message='Você extrapolou o limite negativamente'), django.core.validators.MinValueValidator(limit_value=9999999999999999, message='Você extrapolou o limite positivamente')]),
        ),
        migrations.AddField(
            model_name='client',
            name='rank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rank_of', to='project_auth.rank'),
        ),
    ]
