# Generated by Django 3.1.8 on 2022-01-15 20:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_auth', '0002_auto_20220115_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Rank', 'verbose_name_plural': 'Ranks'},
        ),
        migrations.AlterField(
            model_name='client',
            name='experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999999999, message='Você extrapolou o limite negativamente'), django.core.validators.MinValueValidator(limit_value=-10000, message='Você extrapolou o limite positivamente')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='default_profile.jpeg', upload_to=project_auth.models.upload_perfil_user, verbose_name='Imagem de Perfil'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rank_of', to='project_auth.rank'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='image',
            field=models.ImageField(help_text='É importante que a imagem seja em PNG', upload_to=project_auth.models.upload_rank_images, verbose_name='Imagem do Rank'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização'),
        ),
    ]
