# Generated by Django 3.1.8 on 2021-12-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_auth', '0002_auto_20211211_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='city',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='country',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='state',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='street',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Rua'),
        ),
    ]
